Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0cff7528ff583bf9a
    us-west-1:
      AMI: ami-0bdb828fd58c52235
    us-west-2:
      AMI: ami-a0cfeed8
    eu-west-1:
      AMI: ami-047bb4163c506cd98
    ap-southeast-1:
      AMI: ami-08569b978cc4dfa10
    ap-southeast-2:
      AMI: ami-09b42976632b27e9b
    sa-east-1:
      AMI: ami-07b14488da8ea02a0
Resources:
  SecurityGroupSSHLab04:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite acesso SSH via porta 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroups: 
        - !Ref SecurityGroupSSHLab04
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region