AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Template utilizado para construcao de toda a infraestrutura de redes em uma conta AWS, 
  incluindo componentes como VPC, Internet Gateway, Route Tables, NACLs, Security Groups 
  e instancias EC2.
# Recursos a serem implantados no CloudFormation
Resources:
  # Virtual Private Cloud customizada
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 172.33.0.0/16
      Tags:
        - Key: Name
          Value: cfn-app-vpc