AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Template responsavel por criar uma instancia EC2 em um ambiente
  totalmente privado de conexão via internet (private subnet) para
  restricao de conexoes apenas via Session Manager. Adicionalmente,
  uma role IAM sera criada para servir como instance profile da EC2,
  alem dos endpoints necessarios para permitir conexoes via SSM sem
  acessar a internet publica.
# -----------------------------------------------------------------
# [MAPPINGS]
# Seção responsável por consolidar variáveis utilizadas no template
# de modo a facilitar a configuração de recursos
# -----------------------------------------------------------------
Mappings:
  Network:
    CreateNetworkInfra:
      Flag: True
    CidrBlock:
      VPC: 172.33.0.0/16
      Subnet1a: 172.33.0.0/24
  Compute:
    EC2:
      Type: t2.micro
      ImageId: ami-0cff7528ff583bf9a  
# -----------------------------------------------------------------
# [MAPPINGS]
# Seção responsável por consolidar variáveis utilizadas no template
# de modo a facilitar a configuração de recursos
# -----------------------------------------------------------------
Conditions:
  CreateNetworkInfra: !Equals
    - !FindInMap [Network, CreateNetworkInfra, Flag]
    - True
# -----------------------------------------------------------------
# [RESOURCES]
# Seção responsável por alocar os recursos a serem provisionados em
# tempo de execução deste template.
# -----------------------------------------------------------------
Resources:
  # Estrutura de redes para recepcionar a instância EC2
  VPC:
    Type: AWS::EC2::VPC
    Condition: CreateNetworkInfra
    Properties:
      EnableDnsSupport: True
      EnableDnsHostnames: True
      CidrBlock: !FindInMap [Network, CidrBlock, VPC]
      Tags:
        - Key: Name
          Value: cfn-vpc
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Condition: CreateNetworkInfra
    Properties:
      CidrBlock: !FindInMap [Network, CidrBlock, Subnet1a]
      AvailabilityZone: !Sub ${AWS::Region}a
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: cfn-pvt-subnet-1a
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Condition: CreateNetworkInfra
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: cfn-pvt-rt
  PrivateSubnetRTAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateNetworkInfra
    Properties:
      SubnetId: !Ref PrivateSubnet1a
      RouteTableId: !Ref PrivateRouteTable
  # Role IAM a ser utilizada como instance profile para acesso ao SSM
  IAMSSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-ec2-ssm-instance-profile
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: IAMSSMRole
  # Configurações da EC2
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupName: cfn-https-ssm
      GroupDescription: Permite acesso HTTPS de recursos no range da VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !GetAtt VPC.CidrBlock
          Description: Acesso via porta 443 do intervalo de IPs da VPC
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [Compute, EC2, Type]
      ImageId: !FindInMap [Compute, EC2, ImageId]
      SubnetId: !Ref PrivateSubnet1a
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: cfn-ec2-ssm
  # Endpoints VPC para conexão privada via SSM
  VPCEndpointSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssm'
      VpcId: !Ref VPC
      SubnetIds:
        - !Ref PrivateSubnet1a
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
  VPCEndpointSSMMessages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssmmessages'
      VpcId: !Ref VPC
      SubnetIds:
        - !Ref PrivateSubnet1a
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
  VPCEndpointEC2Messages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ec2messages'
      VpcId: !Ref VPC
      SubnetIds:
        - !Ref PrivateSubnet1a
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
  