AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'Template do CloudFormation para implantação de uma instância EC2
  do tipo t2.micro e um ID de AMI com referência na região us-east-1.'
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cff7528ff583bf9a # Amazon Linux AMI
      Tags:
        - Key: Name
          Value: acg-cfn-instance